services:
  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - youshare_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - youshare_net
    extra_hosts:
      - "host.docker.internal:host-gateway"


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - youshare_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  youshare_net:
    name: youshare_net
    driver: bridge
