spring.datasource.url=jdbc:mysql://localhost:3306/youshare_db?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.error.include-stacktrace=never
api.security.token.secret=${JWT_SECRET:foobar}
api.security.token.validity=${JWT_VALIDITY:2}
api.security.token.zoneoffset=${JWT_ZONEOFFSET:-03:00}